org: titiura
app: aws-node-http-api-project
service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  sendResponse:
    handler: api/handler.sendResponse
    events:
      - httpApi:
          path: /api/results
          method: post
          request:
            schema:
              application/json:
                application/json: ${file(./schemas/sendResponse.json)}
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
