org: titiura
app: aws-node-http-api-project
service: aws-node-http-api-project
frameworkVersion: '3'

params:
  default:
    dbName: db-serverless
  dev:
    connectionString: mongodb://localhost:27017/${self:params.default.dbName}
    salt: wbOGtToR74Lbhyl0XCodIWfmnDyHwdlk
  prod:

provider:
  name: aws
  runtime: nodejs18.x
  environment:
    MONGODB_CONNECTION_STRING: ${param:connectionString}
    MONGODB_DB_NAME: ${param:dbName}
    SALT: ${param:salt}
  region: us-east-1

functions:
  sendResponse:
    handler: api/handlers.sendResponse
    events:
      - httpApi:
          path: /api/results
          method: post
          request:
            schema:
              application/json:
                application/json: ${file(./schemas/sendResponse.json)}
  getResult:
    handler: api/handlers.getResult
    events:
      - httpApi:
          path: /api/results/{id} 
          method: get
  login:
    handler: api/handlers.login
    events:
      - httpApi:
          path: /api/login
          method: post
          request:
            schema:
              application/json:
                application/json: ${file(./schemas/login.json)}
  
plugins:
  - serverless-offline
