org: titiura
app: api-lambda
service: api-lambda
frameworkVersion: '3'

resources:
  extensions:
    S3BucketAlunoscsvtitiura:
      Properties:
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - POST
                - PUT
                - GET
                - HEAD
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              
provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
          Resource:
            - arn:aws:s3:::alunos-csv-titiura/*

functions:
  cadastrarAlunos:
    handler: src/cadastro_batch/aws/index.cadastrarAlunos
    events:
      - s3:
          bucket: alunos-csv-titiura
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv

  simulandoUploadDoCsv:
    handler: src/cadastro_batch/local/index.simulandoUploadDoCsv
    events:
      - httpApi:
          method: post
          path: /alunos/batch
    enabled: false
          
  cadastrarAlunosDoBucketLocal:
    handler: src/cadastro_batch/local/index.cadastrarAlunosDoBucketLocal
    events:
      - s3:
          bucket: alunos-csv-local
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv
    enabled: false
  
plugins:
  - serverless-offline
  - serverless-s3-local
  - serverless-disable-functions

custom:
  serverless-offline:
    httpPort: 3001