org: titiura
app: serverless-2-lambda
service: api-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:GetObject
          Resource:
            - arn:aws:s3:::alunos-csv/*

functions:
  cadastrarAlunos:
    handler: src/cadastro_batch/aws/index.cadastrarAlunos
    events:
      - s3:
          bucket: alunos-csv
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv

  simulandoUploadDoCsv:
    handler: src/cadastro_batch/local/index.simulandoUploadDoCsv
    events:
      - httpApi:
          method: post
          path: /alunos/batch
          cors: true
    enabled: false
          
  cadastrarAlunosDoBucketLocal:
    handler: src/cadastro_batch/local/index.cadastrarAlunosDoBucketLocal
    events:
      - s3:
          bucket: alunos-csv-local
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv
    enabled: false
  
plugins:
  - serverless-offline
  - serverless-s3-local
  - serverless-disable-functions
