org: titiura
app: serverless-3
service: api-alunos
frameworkVersion: '3'

resources:
  extensions:
    S3BucketAlunoscsvtitiura:
      Properties:
        CorsConfiguration:
          CorsRules:
            - AllowedMethods:
                - POST
                - PUT
                - GET
                - HEAD
              AllowedOrigins:
                - "*"
              AllowedHeaders:
                - "*"

params:
  dev:
    bucket: alunos-csv-local
  prod:
    bucket: alunos-csv-titiura

provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 
            - s3:GetObject
          Resource: 
            - arn:aws:s3:::alunos-csv-titiura/*
  environment:
    STAGE: ${sls:stage}
    ACCESS_KEY_ID: ${param:ACCESS_KEY_ID}
    SECRET_ACCESS_KEY: ${param:SECRET_ACCESS_KEY}

functions:
  cadastrarAlunos:
    handler: src/functions/cadastro_batch/index.cadastrarAlunos
    events:
      - s3:
          bucket: alunos-csv-titiura
          event: s3:ObjectCreated:*
          rules:
            - suffix: .csv

  simulandoUploadDoCsv:
    handler: src/functions/cadastro_batch/local/index.simulandoUploadDoCsv
    events:
      - httpApi:
          path: /alunos/batch
          method: post
    enabled: false

  enviarUrlPreassinda:
    handler: src/functions/presignedUrl/index.enviarUrlPreassinada
    events:
      - httpApi:
          path: /alunos/presignedurl
          method: post
  
custom:
  serverless-offline:
    httpPort: 3001

plugins:
  - serverless-offline
  - serverless-s3-local
  - serverless-disable-functions
  